#!/bin/sh

# make sure this script is run by root only
if [ "$(id -u)" != "0" ]; then
	fatal "This script must be run as root"
	exit 1
fi

PACKAGES="coreutils nginx php5-fpm php-apc"
# install apt get packages
for dep in $PACKAGES
do
	echo "\033[47;34m>>> installing package $dep\033[0m"
	apt-get install -q -y $dep || fatal "unable to install $dep"
done


PYLIBS="requests"
# install python dependency
for dep in $PYLIBS
do
	echo "\033[47;34m>>> installing python library $dep\033[0m"
	pip install $dep || fatal "unable to install $dep"
done

echo "Stopping nginx..."
service nginx stop
unlink /etc/nginx/sites-enabled/default

echo "Configuring default site..."
install -v -C --owner=root --mode=u+rwx ../banger/bang.py /usr/local/bin/bang
install -v -C --mode=u+rw etc/nginx/butttton.conf /etc/nginx/sites-available/butttton

echo "Restarting services..."
service php5-fpm restart
service nginx start
